version: '3.8'

services:
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  server:
    build:
      context: ./bff
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
