version: '3.8'

services:
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: todo-frontend
    ports:
      - "8000:8000"

  server:
    build:
      context: ./bff
      dockerfile: Dockerfile
    container_name: todo-bff
    ports:
      - "8001:8001"

  auth-service:
    image: skh02/auth-service:latest
    ports:
      - "8002:8002"
