name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  push_to_registry: 
    name: push docker image to docker hub
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3

    - name: Login to docker repo
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push client image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: skh02/todo-frontend:latest

    - name: Build and push bff image
      uses: docker/build-push-action@v5
      with:
        context: ./bff
        file: ./bff/Dockerfile
        push: true
        tags: skh02/todo-bff:latest

